/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GuiOS.java
 *
 * Created on 29/03/2013, 16:08:30
 */
package br.uninove.visual;

import br.uninove.modelo.OrdemServicoBean;
import br.uninove.modelo.OrdemServicoDao;
import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.util.Date;
import java.sql.Timestamp;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Roberto Silva
 */
public class GuiOS extends javax.swing.JInternalFrame {

    /** Creates new form GuiOS */
    public GuiOS() {
        initComponents();
    }

     public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2,
                (d.height - this.getSize().height) / 2);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lblSolicitante = new javax.swing.JLabel();
        lblSetor = new javax.swing.JLabel();
        lblContato = new javax.swing.JLabel();
        lblEquipamento = new javax.swing.JLabel();
        lblSerial = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        tfSolicitante = new javax.swing.JTextField();
        cbSetor = new javax.swing.JComboBox();
        tfContato = new javax.swing.JFormattedTextField();
        cbEquipamento = new javax.swing.JComboBox();
        tfNSerial = new javax.swing.JTextField();
        tfModelo = new javax.swing.JTextField();
        lblDescricao = new javax.swing.JLabel();
        lblObs = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taDescricao = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        taObservacao = new javax.swing.JTextArea();
        btnEnviar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setClosable(true);
        setIconifiable(true);
        setTitle("Ordem de Serviço");

        lblSolicitante.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblSolicitante.setText("Solicitante:");

        lblSetor.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblSetor.setText("Setor:");

        lblContato.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblContato.setText("Contato:");

        lblEquipamento.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblEquipamento.setText("Equipamento:");

        lblSerial.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblSerial.setText("Nº.Serial:");

        lblModelo.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblModelo.setText("Modelo:");

        cbSetor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<-- Selecione -->", "Vendas", "Marketing", "Publicidade", "Financeiro", "Produção", "Engenharia", "Almoxarifado", "Logística", "Recurso Humanos", "Outros" }));

        try {
            tfContato.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        cbEquipamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<-- Selecione -->", "Teclado", "Mouse", "Monitor", "Caixa de Som", "Web Câmera\t", "Impressora", "Scanner", "Outros" }));

        lblDescricao.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblDescricao.setText("Descrição do defeito ou atividade: ");

        lblObs.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblObs.setText("Observação:");

        taDescricao.setColumns(20);
        taDescricao.setRows(5);
        jScrollPane2.setViewportView(taDescricao);

        taObservacao.setColumns(20);
        taObservacao.setRows(5);
        jScrollPane3.setViewportView(taObservacao);

        btnEnviar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 11));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)
                        .addContainerGap())
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblObs)
                            .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblDescricao)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                                .addComponent(lblContato, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(lblEquipamento)
                                                .addComponent(cbEquipamento, 0, 161, Short.MAX_VALUE)
                                                .addComponent(tfContato))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblSerial)
                                                .addComponent(tfNSerial, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)))
                                        .addComponent(tfSolicitante, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblSolicitante, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblSetor)
                                        .addComponent(cbSetor, 0, 207, Short.MAX_VALUE)
                                        .addComponent(lblModelo)
                                        .addComponent(tfModelo))))
                            .addGap(35, 35, 35)))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancelar, btnEnviar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSetor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSolicitante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblContato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEquipamento)
                            .addComponent(lblSerial))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNSerial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblModelo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lblDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblObs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnviar)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCancelar, btnEnviar});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        
        if(isFieldsOK()){
           try{ 
            //cria o objeto O.S   
            OrdemServicoBean osBean=new OrdemServicoBean();
            //seta as variaveis do Objeto O.S
            osBean.setOs_solicitante(tfSolicitante.getText().trim());
            osBean.setOs_setor((String)cbSetor.getSelectedItem());
            osBean.setOs_contato((String)tfContato.getText().trim());
            osBean.setOs_equipamento((String)cbEquipamento.getSelectedItem());
            osBean.setOs_serial(tfNSerial.getText().trim());
            osBean.setOs_modelo(tfModelo.getText().trim());
            osBean.setOs_descricao(taDescricao.getText().trim());
            osBean.setOs_observacao(taObservacao.getText().trim());
            osBean.setOs_data_hora(new Timestamp(new Date().getTime()));
            osBean.setOs_status("PENDENTE");
            
            //cria o objeto de controle p/persistencia com Banco de dados
            OrdemServicoDao dao=new OrdemServicoDao();
            //inseri no banco
            dao.insert(osBean);
            
            //chamo um metodo para reiniciar o formulario 
            inicializaCampos();
            
           }catch(Exception e){
               e.printStackTrace();
               
               JOptionPane.showMessageDialog(null, 
                       "Ocorreu um erro, causa: "+e.getMessage(),
                       "Ordem de Serviço",
                       JOptionPane.ERROR_MESSAGE);
           }
        }
        
    }//GEN-LAST:event_btnEnviarActionPerformed

    /*
     Verifica campos obrigatórios
     */
    private boolean isFieldsOK(){
        
        if(tfSolicitante.getText().trim().length() == 0){
             JOptionPane.showMessageDialog(null, 
                       "Ops, preencha o campo solicitante.",
                       "Ordem de Serviço",
                       JOptionPane.WARNING_MESSAGE);
             tfSolicitante.requestFocus();
            return false;
        }
        
        if(cbSetor.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null, 
                       "Ops, selecione um setor.",
                       "Ordem de Serviço",
                       JOptionPane.WARNING_MESSAGE);
            cbSetor.requestFocus();
            return false;
        }
        
        if(taDescricao.getText().trim().length()== 0){
             JOptionPane.showMessageDialog(null, 
                       "Ops, Preencha o campo descrição do defeito...",
                       "Ordem de Serviço",
                       JOptionPane.WARNING_MESSAGE);
             taDescricao.requestFocus();
            return false;
        }
            
        return true;
    }
    
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        inicializaCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JComboBox cbEquipamento;
    private javax.swing.JComboBox cbSetor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblContato;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblEquipamento;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblObs;
    private javax.swing.JLabel lblSerial;
    private javax.swing.JLabel lblSetor;
    private javax.swing.JLabel lblSolicitante;
    private javax.swing.JTextArea taDescricao;
    private javax.swing.JTextArea taObservacao;
    private javax.swing.JFormattedTextField tfContato;
    private javax.swing.JTextField tfModelo;
    private javax.swing.JTextField tfNSerial;
    private javax.swing.JTextField tfSolicitante;
    // End of variables declaration//GEN-END:variables

    private void inicializaCampos() {
        //limpa campos em formulario
        limparCampos(this.getContentPane());
        //limpa TextArea, como fica em um ScrolPane, então limpo assim
        taDescricao.setText("");
        taObservacao.setText("");
        //volta ao 1º indice
        cbEquipamento.setSelectedIndex(0);
        cbSetor.setSelectedIndex(0);
        //seleciona o 1° campo
        tfSolicitante.requestFocus();
    }
    
    public static void limparCampos(Container container) {
        Component components[] = container.getComponents();

        for (Component component : components) {
             
            if (component instanceof JFormattedTextField) {
                JFormattedTextField field = (JFormattedTextField) component;
                field.setValue(null);
            }else if (component instanceof JTextField) {
                JTextField field = (JTextField) component;
                field.setText("");
            }  else if (component instanceof JPasswordField) {
                JPasswordField password = (JPasswordField) component;
                password.setText("");
            }

        }

    }
}
