/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GuiSobre.java
 *
 * Created on 29/03/2013, 15:26:38
 */
package br.uninove.visual;

import java.awt.Dimension;

/**
 *
 * @author Roberto Silva
 */
public class GuiSobre extends javax.swing.JInternalFrame {

    /** Creates new form GuiSobre */
    public GuiSobre() {
        initComponents();
    }

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2,
                (d.height - this.getSize().height) / 2);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblAutor = new javax.swing.JLabel();
        lblLicenca = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        tfAutor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taLicenca = new javax.swing.JTextArea();
        lblDisc_pro = new javax.swing.JLabel();
        tfDisc_pro = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        taDescricao = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setTitle("Sobre...");
        setPreferredSize(new java.awt.Dimension(334, 459));

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTitulo.setText("Ordem de Serviço T.I");

        lblAutor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAutor.setText("Autor:");

        lblLicenca.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblLicenca.setText("Licença:");

        lblDescricao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDescricao.setText("Descrição:");

        tfAutor.setEditable(false);
        tfAutor.setText("Grupo 2");

        taLicenca.setColumns(20);
        taLicenca.setEditable(false);
        taLicenca.setRows(5);
        taLicenca.setText("Licença Pública da GNU \n(GNU General Public License), \nconforme publicada pela Free\nSoftware Foundation.");
        jScrollPane1.setViewportView(taLicenca);

        lblDisc_pro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDisc_pro.setText("Disciplina/Professor:");

        tfDisc_pro.setEditable(false);
        tfDisc_pro.setText("Engenharia de Software/André Rivas");

        taDescricao.setColumns(20);
        taDescricao.setEditable(false);
        taDescricao.setRows(5);
        taDescricao.setText("Sistema de Ordem de serviço,\npara facilitar o assessoramento\ndo setor de Tecnologia da \nInformação (TI) com todos \nos setores.");
        jScrollPane2.setViewportView(taDescricao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTitulo)
                    .addComponent(lblDisc_pro)
                    .addComponent(lblDescricao)
                    .addComponent(lblLicenca)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                    .addComponent(lblAutor)
                    .addComponent(tfAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDisc_pro))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(14, 14, 14)
                .addComponent(lblAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDisc_pro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfDisc_pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(lblDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblLicenca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblDisc_pro;
    private javax.swing.JLabel lblLicenca;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextArea taDescricao;
    private javax.swing.JTextArea taLicenca;
    private javax.swing.JTextField tfAutor;
    private javax.swing.JTextField tfDisc_pro;
    // End of variables declaration//GEN-END:variables
}
